# Generated by Django 2.0.2 on 2018-05-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20180503_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_data',
            field=models.ForeignKey(on_delete=True, to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_data',
            field=models.ForeignKey(on_delete=True, to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_data',
            field=models.ForeignKey(on_delete=True, to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='qvoter',
            name='user',
            field=models.ForeignKey(on_delete=True, to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='user',
            field=models.ForeignKey(on_delete=True, to='main_app.Profil'),
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
