# Generated by Django 2.0.2 on 2018-05-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_auto_20180509_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='qa.Categorie'),
        ),
    ]
