# Generated by Django 2.0.2 on 2018-05-09 23:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_auto_20180509_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
