# Generated by Django 2.0.2 on 2018-05-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
