# Generated by Django 2.0.2 on 2018-05-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profil_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='photos', verbose_name='My Photo'),
        ),
    ]
